import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Spades</h1>
        <h2>An Asexual-Styled VSCode Theme</h2>
        <Image src="/img/css.png" width={417} height={444} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
