import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.h1}>Spades</h1>
        <h2 className={styles.h2}>
          A minimal, Asexual-styled VSCode Theme inspired by the Microsoft
          Palenight Theme
        </h2>
        <div className={styles.editor}>
          <Image
            src="/img/example.png"
            width={960}
            height={490}
            quality={100}
          />
        </div>
        <h2>Color Palette</h2>
        <div className={styles.palette}></div>
      </main>
    </div>
  );
}
